In [87]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할때 사용하는 자료구조
# 0차원 텐서 : 스칼라 - 단일 데이터
# 1차원 텐서(벡터) : 리스트 형태 [1,2,3,4]
# 2차원 텐서(행렬) : 행과 열로 이루어진 데이터 표데이터, 흑백 이미지(가로픽셀 * 세로픽셀)
# 3차원 텐서 : 컬러 이미지 흑백이미지 + 채널정보(R G B)
# 고차원 텐서 : 동영상 : 이미지개수 * 가로픽셀 * 세로픽셀 * 채널정보

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병렬연산에 유리
# 딥러닝 프레임워크 : 텐서플로, 파이토치

In [88]:
# %pip install torch torchvision

In [89]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4)
x

tensor([[0.5467, 1.6155, 1.5689, 0.3604],
        [0.6585, 0.9415, 1.6128, 1.0934],
        [1.0343, 0.4105, 0.9633, 1.2134]])

In [90]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.4320, 0.8433, 0.5037, 0.9727],
        [0.6048, 0.7251, 0.0330, 0.8630],
        [0.7857, 0.7978, 0.9194, 0.1344]])

In [91]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [92]:
# 1로 채워진 텐서
x = torch.ones(3,4, dtype=torch.long)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [93]:
import numpy as np
print( torch.tensor( [3.5,3,2.1] ) )
print( np.array( [3.5,3,2.1] )  )

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [94]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x, dtype= torch.float)
x,  y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 0.6410, -0.2444, -0.0215,  2.0130],
         [-0.3597, -0.8308, -1.3207, -0.6646],
         [-0.1310, -0.4459,  0.2628, -1.8682]]))

In [95]:
import torch
x = torch.rand(3,4)
y = torch.rand(3,4)
x ,  y, x+y

(tensor([[0.4731, 0.1955, 0.3305, 0.6991],
         [0.8344, 0.2819, 0.1961, 0.7160],
         [0.8188, 0.5689, 0.9699, 0.8560]]),
 tensor([[0.4749, 0.9788, 0.9923, 0.4208],
         [0.4247, 0.8628, 0.2520, 0.5531],
         [0.8759, 0.1953, 0.3265, 0.2169]]),
 tensor([[0.9480, 1.1743, 1.3228, 1.1199],
         [1.2591, 1.1447, 0.4481, 1.2691],
         [1.6948, 0.7642, 1.2964, 1.0730]]))

In [96]:
torch.add(x,y)

tensor([[0.9480, 1.1743, 1.3228, 1.1199],
        [1.2591, 1.1447, 0.4481, 1.2691],
        [1.6948, 0.7642, 1.2964, 1.0730]])

In [97]:
#in-place   y = y + x   y += x
y.add_(x)

tensor([[0.9480, 1.1743, 1.3228, 1.1199],
        [1.2591, 1.1447, 0.4481, 1.2691],
        [1.6948, 0.7642, 1.2964, 1.0730]])

In [98]:
y

tensor([[0.9480, 1.1743, 1.3228, 1.1199],
        [1.2591, 1.1447, 0.4481, 1.2691],
        [1.6948, 0.7642, 1.2964, 1.0730]])

In [99]:
# 행렬 곱셈 
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y),x@y # 파이썬 3.5  x@y

(tensor([[0.8830, 0.6789, 0.2227, 0.3339],
         [0.7280, 0.0089, 0.5989, 0.8301],
         [0.3991, 0.2501, 0.4952, 0.5353]]),
 tensor([[0.1350, 0.2766, 0.8705, 0.3887, 0.2504],
         [0.4335, 0.6573, 0.2348, 0.2376, 0.7417],
         [0.5468, 0.0991, 0.1792, 0.5472, 0.2221],
         [0.6468, 0.4583, 0.7412, 0.7605, 0.7203]]),
 tensor([[0.7513, 0.8656, 1.2156, 0.8804, 1.0147],
         [0.9666, 0.6470, 1.3584, 1.2441, 0.9199],
         [0.7793, 0.5692, 0.8917, 0.8926, 0.7810]]),
 tensor([[0.7513, 0.8656, 1.2156, 0.8804, 1.0147],
         [0.9666, 0.6470, 1.3584, 1.2441, 0.9199],
         [0.7793, 0.5692, 0.8917, 0.8926, 0.7810]]))

In [100]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item() )

(tensor(0.1971), 0.1970820426940918, torch.Tensor, float)

In [101]:
# 텐서 크기 변경 reshapem view   numpy 동일한 기능 reshape
x = torch.rand(4,4)
y = x.view(-1) # -1 자동계산
x, y, x.shape, y.shape

(tensor([[0.7266, 0.9107, 0.9443, 0.8031],
         [0.3916, 0.8580, 0.3068, 0.2161],
         [0.5493, 0.4008, 0.3663, 0.2296],
         [0.9811, 0.3051, 0.9835, 0.1724]]),
 tensor([0.7266, 0.9107, 0.9443, 0.8031, 0.3916, 0.8580, 0.3068, 0.2161, 0.5493,
         0.4008, 0.3663, 0.2296, 0.9811, 0.3051, 0.9835, 0.1724]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [102]:
# x  4 by 4
# view : reshape # 텐서 모양 변경
# size : shape # 텐서 모양 확인
# 가독성  view size 사용되었다는 것은 해당 자료구조가 텐서라는 것을 명시
x.view(-1, 8), x.size()

(tensor([[0.7266, 0.9107, 0.9443, 0.8031, 0.3916, 0.8580, 0.3068, 0.2161],
         [0.5493, 0.4008, 0.3663, 0.2296, 0.9811, 0.3051, 0.9835, 0.1724]]),
 torch.Size([4, 4]))

In [103]:
# 텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [104]:
# 넘파이 -> 텐서
a = np.array([1,2,3,4,5])
b = torch.from_numpy(a)
b

tensor([1, 2, 3, 4, 5])

In [105]:
# GPU 사용
import torch
if torch.cuda.is_available():
    device = torch.device('cuda') # gpu
    # 텐서들은 gpu에서 연산되기 떄문에 생성을 gpu에서 생성
    x = torch.ones(5, device=device) # gpu
    y = torch.ones(5) # cpu
    y = y.to(device) # cpu->gpu로 이동
    z = x + y # gpu, cpu에 있으면 연산이 안됨
    print(f'GPU 연산결과 : {z}')
    print(f'다시 CPU로 : {z.to("cpu", torch.double) }')
else:
    print('CUDA를 사용할 수 없습니다.')

CUDA를 사용할 수 없습니다.


In [106]:
# 행렬의 곱
# ( x,y ) * ( x1,y1 )
# y, x1의 차수는 같아야한다
# 행렬 곱의 결과는 x , y1

# 텐서는 딥러닝을 위해 만든 자료구조, 내부에 gpu 연산에 특화된 구조, 일반적인 모양은 넘파이와 동일
# 텐서는 gpu연산을 지원

In [107]:
# 자동 미분(Autograd) 매 계산과정마다 해당 계산과정의 미분값을 저장
# 파이토치 requires_grad = True 로 설정하면 계산그래프라는 형태로 기록 - 동영상 녹화와 비슷한 원리
# .backword() 호출하면 이 과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해서 최종 기울기를 얻는다

In [108]:
x = torch.ones(2,2, requires_grad=True)
x, x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [109]:
y = x + 2  # y도 계산 그래프에 추가
print(y, y.grad_fn)
z = y*y*3
out = z.mean()
z, out

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x000002019814ABC0>


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [111]:
# 기울기 구하는 과정을 역전파 --> 기울기 계산
# 최종결과가 out에서부터 시작해서 계산그래프를 거꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 x에 대해서 미분
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [ ]:
# out = 1/4(z1+z2+z3+z4)
# z = 3y^2
# y = x + 2

# d-out/dxi = 